# Generated by Django 4.0.5 on 2022-12-04 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkMovementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(auto_now=True)),
                ('exit_date', models.DateField(null=True)),
                ('validate_date', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('plate', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclemodel')),
            ],
            options={
                'db_table': 'TB_PARKMOVEMENT',
            },
        ),
    ]
