# Generated by Django 4.0.5 on 2022-06-08 20:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(auto_now=True)),
                ('exit_date', models.DateField()),
                ('validate_date', models.DateField()),
                ('value', models.FloatField()),
                ('plate', models.CharField(max_length=50)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'TB_PARKMOVEMENT',
            },
        ),
    ]
