# Generated by Django 4.0.5 on 2022-06-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park_movement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkmovement',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
