# Generated by Django 4.0.5 on 2022-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_movement', '0002_rename_vehicle_id_parkmovement_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
