# Generated by Django 4.0.5 on 2022-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_movement', '0003_alter_parkmovement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='exit_date',
            field=models.DateField(null=True),
        ),
    ]
