# Generated by Django 4.0.5 on 2022-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_movement', '0004_alter_parkmovement_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='validate_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
