# Generated by Django 4.0.5 on 2022-12-04 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=10)),
                ('kind', models.IntegerField(choices=[(1, 'Moto'), (2, 'Carro')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel')),
            ],
            options={
                'db_table': 'TB_CUSTOMER_VEHICLES',
            },
        ),
    ]
