# Generated by Django 4.0.5 on 2022-06-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='novo',
        ),
    ]
