# Generated by Django 4.0.5 on 2022-06-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicle_novo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
