# Generated by Django 4.0.5 on 2022-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rename_customer_id_vehicle_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='novo',
            field=models.IntegerField(default=0),
        ),
    ]
