# Generated by Django 4.0.5 on 2022-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle_novo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='novo',
        ),
    ]
